 .. raw:: html

   <!-- NB: using raw:: directive in order to accurately tag metadata -->

     <a rel="author">Département Informatique
       (<a href="http://iut.univ-lyon1.fr/">IUT Lyon 1</a>)
          </a>

     <a rel="license"
        href="http://creativecommons.org/licenses/by-sa/3.0/fr/deed.fr">
        <p><img alt="Creative Commons License" style="border-width:0"
             src="_static/cc.png" /></p></a>

     <p class="license">Ce travail est sous licence
     <a rel="license"
        href="http://creativecommons.org/licenses/by-sa/3.0/fr/deed.fr">
        Creative Commons Attribution-ShareAlike 3.0 France</a>.</p>


.. only:: not(html) and not(slides)

   .. fallback for non HTML content

   Département Informatique, `IUT Lyon 1 <http://iut.univ-lyon1.fr/>`_

   .. figure:: _static/cc.png
      :target: http://creativecommons.org/licenses/by-sa/3.0/fr/deed.fr

   Ce travail est sous licence
   `Creative Commons Attribution-ShareAlike 3.0 France`_

.. _Creative Commons Attribution-ShareAlike 3.0 France: http://creativecommons.org/licenses/by-sa/3.0/fr/deed.fr
